[tool.poetry]
name = "generator"
version = "0.1.0"
description = ""
authors = ["VpgMackan <dev@mndev.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pika = "^1.3.2"
pydantic-settings = "^2.10.1"
psycopg2-binary = "^2.9.10"
sqlalchemy = "^2.0.41"
pgvector = "^0.4.1"
httpx = "^0.28.1"
structlog = "^24.1.0"
scikit-learn = "^1.7.2"
librosa = "^0.11.0"
pydub = "^0.25.1"
boto3 = "^1.40.35"

[tool.poetry.scripts]
generator = "generator.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
